#!/bin/bash

# ============================================================
# JANKYBORDERS CONFIGURATION
# File: ~/.config/borders/bordersrc
#file: dotfiles/borders/bordersrc
# ============================================================

# Cyan: #91FFFF
# JankyBorders color format: 0xAARRGGBB
# FF = fully opaque
# 91FFFF = cyan

options=(
    style=round
    width=2.0
    hidpi=on
    active_color=0xFF91FFFF
    inactive_color=0x00313A31
    background_color=0x00000000
)

borders "${options[@]}"
